---
title: "Use the Armadillo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using Armadillo to perform analysis with DataSHIELD}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## Usage
When you start to use Armadillo as a backend for DataSHIELD you can use the `DSMolgenisArmadillo` package for research purposes.
There is a default workflow in DataSHIELD to do analysis. There are several steps that you need to take.

- [Install](#install)
- [Authenticate](#authenticate)
- [Assign data](#assign-data)
- [Transform data](#transform-data)
- [Performing analysis](#performing-analysis)
- [Workspaces](#workspaces)

### Install
The DataSHIELD Armadillo package is available on the MOLGENIS CRAN (https://registry.molgenis.org/repository/R). You can install it by executing the following code-block:


```r
install.packages("DSI")
install.packages("DSMolgenisArmadillo", repos = "https://registry.molgenis.org/repository/R", dependencies = TRUE)
```

Make sure you install the DataSHIELD client (`dsBaseClient`) to perform the actual analysis. This needs to be a client which is version 6.0 or higher.


```r
# install the DataSHIELD client
install.packages("dsBase", repos = c("http://cran.datashield.org", "http://cran.us.r-project.org"), dependencies = TRUE)
#> Warning in install.packages :
#>   unable to access index for repository http://cran.datashield.org/bin/macosx/el-capitan/contrib/3.6:
#>   cannot open URL 'http://cran.datashield.org/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
#> installing the source package 'dsBase'
```

**Experimental versions**

If you are interested in using exeperimental versions you can use our own CRAN repository:


```r
# install experimental Armadillo client
install.packages("DSMolgenisArmadillo", repos = "https://registry.molgenis.org/repository/r-hosted-snapshots")
```

Load the necessary packages.


```r
library(dsBaseClient)
library(DSMolgenisArmadillo)
```

### Authenticate
The login procedure consists of building a login dataframe and performing the login on the Armadillo server. The important part is to specify the driver. This should be `ArmadilloDriver`. 

We support authentication 2 flows. 
- as normal user (using oauth on the central authentication server)
- as superuser (using basic authentication, username and password based)

We are currently only using the oauth flow in production environments.
- Authenticate using the authentication server
- Authenticate using the superuser credentials


```r
# method 1: using oauth on the central server
# specify server url
armadillo_url <- "https://armadillo.dev.molgenis.org"

# get token from central authentication server
token <- armadillo.get_token(armadillo_url)
#> [1] "We're opening a browser so you can log in with code ZDGJFZ"
token
#> [1] "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlcwbmltejhpYU9DLW16OXNaTVRiVzRfbFdMMCJ9.eyJhdWQiOiI3ODliOTQxNy1jYTJiLTQ3MDctYWI5Yy00NzEzNzNkOTFiYTAiLCJleHAiOjE1OTg2MDQyNjgsImlhdCI6MTU5ODYwMDY2OCwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1vbGdlbmlzLm9yZyIsInN1YiI6IjliY2E3MzJjLThjMjEtNDNkMi1iNTU1LTI3YWZiZjgyZTJmMyIsImF1dGhlbnRpY2F0aW9uVHlwZSI6IlBBU1NXT1JEIiwiZW1haWwiOiJzLmhhYWttYUB1bWNnLm5sIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJ5NkJwX3JpZzBTX09obTVrTUdJMWFBIiwiYXBwbGljYXRpb25JZCI6Ijc4OWI5NDE3LWNhMmItNDcwNy1hYjljLTQ3MTM3M2Q5MWJhMCIsInJvbGVzIjpbIlNVIl0sInBvbGljeSI6InJlYWR3cml0ZSJ9.iIX9xP-2_HHBtN28F76GMz4gQMETeeLk-40L91AZmudrHOzzMzv_SrGHmofP670DNwbUG8HBQJeFYZtS89VemO_5PZDkS1vdwgZouU2C48DHzqHSDU_23FcVABmQ3UN5_ByJUOkvF4pM16rvGPFG1uyxVq-mlsVKK_cYd_VOcGLIqdL4qttcFnctLN289L9C4-_pu1YmAJpFEIojkI-AxMIrgbHd69bh6ET06WCDhLwC7jeMKqzapE5QXru7Wu3_AQV_crMlvDA5NsSfTgG2wHfuZFq8tXpLnKf6BBrTPUvNUvGoHrt-X09KtlkRAmELcPUN-eEsIZUnPUJex7ENhw"
# build the login dataframe
builder <- DSI::newDSLoginBuilder()
builder$append(server = "armadillo",
               url = armadillo_url,
               user = "",
               password = "",
               token = token,
               table = "gecko/2_1-core-1_0/nonrep",
               driver = "ArmadilloDriver")

# create loginframe
logindata <- builder$build()
logindata
#>      server                                url                     table resource          driver user password
#> 1 armadillo https://armadillo.dev.molgenis.org gecko/2_1-core-1_0/nonrep          ArmadilloDriver              
#>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  token
#> 1 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlcwbmltejhpYU9DLW16OXNaTVRiVzRfbFdMMCJ9.eyJhdWQiOiI3ODliOTQxNy1jYTJiLTQ3MDctYWI5Yy00NzEzNzNkOTFiYTAiLCJleHAiOjE1OTg2MDQyNjgsImlhdCI6MTU5ODYwMDY2OCwiaXNzIjoiaHR0cHM6Ly9hdXRoLm1vbGdlbmlzLm9yZyIsInN1YiI6IjliY2E3MzJjLThjMjEtNDNkMi1iNTU1LTI3YWZiZjgyZTJmMyIsImF1dGhlbnRpY2F0aW9uVHlwZSI6IlBBU1NXT1JEIiwiZW1haWwiOiJzLmhhYWttYUB1bWNnLm5sIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF0X2hhc2giOiJ5NkJwX3JpZzBTX09obTVrTUdJMWFBIiwiYXBwbGljYXRpb25JZCI6Ijc4OWI5NDE3LWNhMmItNDcwNy1hYjljLTQ3MTM3M2Q5MWJhMCIsInJvbGVzIjpbIlNVIl0sInBvbGljeSI6InJlYWR3cml0ZSJ9.iIX9xP-2_HHBtN28F76GMz4gQMETeeLk-40L91AZmudrHOzzMzv_SrGHmofP670DNwbUG8HBQJeFYZtS89VemO_5PZDkS1vdwgZouU2C48DHzqHSDU_23FcVABmQ3UN5_ByJUOkvF4pM16rvGPFG1uyxVq-mlsVKK_cYd_VOcGLIqdL4qttcFnctLN289L9C4-_pu1YmAJpFEIojkI-AxMIrgbHd69bh6ET06WCDhLwC7jeMKqzapE5QXru7Wu3_AQV_crMlvDA5NsSfTgG2wHfuZFq8tXpLnKf6BBrTPUvNUvGoHrt-X09KtlkRAmELcPUN-eEsIZUnPUJex7ENhw
#>   options
#> 1

datashield.logout(conns)

# login into server
conns <- datashield.login(logins = logindata, assign = FALSE)
#> 
#> Logging into the collaborating servers
#>   Logged in all servers [================================================================] 100% / 0s
```

The superuser has a simple username and password which you can fill in in the login dataframe.

### Assign data
To work with DataSHIELD you need to be able to query data. You can do this by assigning data in the Armadillo service.


```r
# assign data in the Armadillo service
datashield.assign.table(conns = conns,
                        table = "gecko/2_1-core-1_0/nonrep",
                        symbol = "D",
                        variables = c("recruit_age", "child_id"))
#>   Assigned all table (D <- ...) [========================================================] 100% / 0s
```

#### Symbol assignment
For each of the tables assigned in the Aramdillo a symbol is created in each of the servers. 
You can remove the symbol from the workspace on the server by executing the following code:


```r
# list the current symbols
datashield.symbols(conns)
#> $armadillo
#> [1] "D"
# remove the symbol
datashield.rm(conns = conns, "D")
# list the current symbols without the deleted one
datashield.symbols(conns)
#> $armadillo
#> character(0)
```

#### Assign data using expressions
You can assign values from tables to symbols, but you can use hardcoded expressions as well.


```r
# assign random data to 'K'
datashield.assign.expr(conns = conns, symbol = "K", "c(10,50,100)")
```


```r
# calculate the mean of 'K' to see that the assignment has worked
ds.mean("K", datasources = conns)
#> $Mean.by.Study
#>           EstimatedMean Nmissing Nvalid Ntotal
#> armadillo      53.33333        0      3      3
#> 
#> $Nstudies
#> [1] 1
#> 
#> $ValidityMessage
#>           ValidityMessage 
#> armadillo "VALID ANALYSIS"
```

#### Assign data from tables
When you have assigned symbols in R, you check which tables (`data.frame`'s) are available on the Armadillo.


```r
# assign the data again
datashield.assign.table(conns = conns, 
                        table = "gecko/2_1-core-1_0/nonrep", 
                        symbol = "core_nonrep")
```


```r
# check the columns in the non-repeated data
ds.colnames("core_nonrep", datasources = conns)
#> $armadillo
#>   [1] "row_id"              "child_id"            "mother_id"           "cohort_id"           "preg_no"             "child_no"            "coh_country"        
#>   [8] "recruit_age"         "cob_m"               "ethn1_m"             "ethn2_m"             "ethn3_m"             "agebirth_m_y"        "agebirth_m_d"       
#>  [15] "death_m"             "death_m_age"         "prepreg_weight"      "prepreg_weight_mes"  "prepreg_weight_ga"   "latepreg_weight"     "latepreg_weight_mes"
#>  [22] "latepreg_weight_ga"  "preg_gain"           "preg_gain_mes"       "height_m"            "height_mes_m"        "prepreg_dia"         "preg_dia"           
#>  [29] "preg_thyroid"        "preg_fever"          "preeclam"            "preg_ht"             "asthma_m"            "prepreg_psych"       "preg_psych"         
#>  [36] "ppd"                 "prepreg_smk"         "prepreg_cig"         "preg_smk"            "preg_cig"            "prepreg_alc"         "prepreg_alc_unit"   
#>  [43] "preg_alc"            "preg_alc_unit"       "folic_prepreg"       "folic_preg12"        "folic_post12"        "parity_m"            "preg_plan"          
#>  [50] "mar"                 "ivf"                 "outcome"             "mode_delivery"       "plac_abrup"          "cob_p"               "cob_p_fath"         
#>  [57] "ethn1_p"             "ethn2_p"             "ethn3_p"             "ethn_p_fath"         "agebirth_p_y"        "agebirth_p_d"        "agebirth_p_fath"    
#>  [64] "death_p"             "death_p_age"         "death_p_fath"        "weight_f1"           "weight_mes_f1"       "weight_f1_fath"      "height_f1"          
#>  [71] "height_mes_f1"       "height_f1_fath"      "dia_bf"              "asthma_bf"           "psych_bf"            "smk_p"               "smk_cig_p"          
#>  [78] "smk_fath"            "birth_month"         "birth_year"          "apgar"               "neo_unit"            "sex"                 "plurality"          
#>  [85] "ga_lmp"              "ga_us"               "ga_mr"               "ga_bj"               "birth_weight"        "birth_length"        "birth_head_circum"  
#>  [92] "weight_who_ga"       "plac_weight"         "con_anomalies"       "major_con_anomalies" "cer_palsy"           "sibling_pos"         "death_child"        
#>  [99] "death_child_age"     "breastfed_excl"      "breastfed_any"       "breastfed_ever"      "solid_food"          "childcare_intro"     "cats_preg"          
#> [106] "dogs_preg"           "cats_quant_preg"     "dogs_quant_preg"
```


### Subsetting data
Before you are working with the data you can subset to a specific range of variables you want to use in the set.


```r
# assign the repeated data to reshape
datashield.assign.table(conns = conns,
                        table = "gecko/2_1-core-1_0/yearlyrep",
                        symbol = "core_yearlyrep")

# check dimensions of repeatead measures
ds.dim("core_yearlyrep", datasources = conns)
#> $`dimensions of core_yearlyrep in armadillo`
#> [1] 19000    34
#> 
#> $`dimensions of core_yearlyrep in combined studies`
#> [1] 19000    34

# subset the data to the first 2 years
ds.dataFrameSubset(df.name = 'core_yearlyrep', newobj = 'core_yearlyrep_1_3', V1.name = "core_yearlyrep$age_years", V2.name = "2", Boolean.operator  = '<=') 
#>   Aggregated (dataFrameSubsetDS1("core_yearlyrep", "core_yearlyrep$age_years", ) [=======] 100% / 1s
#>   Assigned expr. (core_yearlyrep_1_3 <- dataFrameSubsetDS2("core_yearlyrep", "core_yearlyrep$age_...
#> $is.object.created
#> [1] "A data object <core_yearlyrep_1_3> has been created in all specified data sources"
#> 
#> $validity.check
#> [1] "<core_yearlyrep_1_3> appears valid in all sources"

# check the columns
ds.colnames("core_yearlyrep_1_3", datasources = conns)
#> $armadillo
#>  [1] "row_id"            "child_id"          "age_years"         "cohab_"            "occup_m_"          "occupcode_m_"      "edu_m_"           
#>  [8] "occup_f1_"         "occup_f1_fath"     "occup_f2_"         "occup_f2_fath"     "occupcode_f1_"     "occupcode_f1_fath" "occupcode_f2_"    
#> [15] "occupcode_f2_fath" "edu_f1_"           "edu_f1_fath"       "edu_f2_"           "edu_f2_fath"       "childcare_"        "childcarerel_"    
#> [22] "childcareprof_"    "childcarecentre_"  "smk_exp"           "pets_"             "cats_"             "cats_quant_"       "dogs_"            
#> [29] "dogs_quant_"       "mental_exp"        "hhincome_"         "fam_splitup"       "famsize_child"     "famsize_adult"

# check dimensions again
ds.dim("core_yearlyrep_1_3", datasources = conns)
#> $`dimensions of core_yearlyrep_1_3 in armadillo`
#> [1] 3000   34
#> 
#> $`dimensions of core_yearlyrep_1_3 in combined studies`
#> [1] 3000   34
```


### Transform data
In general you need 2 methods to work with data that is stored in long format, the `reshape` and `merge` functions in DataSHIELD. You can reshape data with the Armadillo to transform data from [wide-format to long-format](https://www.theanalysisfactor.com/wide-and-long-data/) and vice versa. 

You can do this using the `ds.reshape` function:


```r
# reshape the data for the wide-format variables (yearlyrep)
ds.reShape(data.name='core_yearlyrep_1_3',
           timevar.name = 'age_years',
           idvar.name = 'child_id',
           v.names=c("pets_", "cats_", "dogs_"),
           direction = 'wide',
           newobj = "core_yearlyrep_1_3_wide",
           datasources = conns
)
#>   Assigned expr. (core_yearlyrep_1_3_wide <- reShapeDS("core_yearlyrep_1_3", NULL, "pets_,cats_,d...
#> $is.object.created
#> [1] "A data object <core_yearlyrep_1_3_wide> has been created in all specified data sources"
#> 
#> $validity.check
#> [1] "<core_yearlyrep_1_3_wide> appears valid in all sources"
```


```r
# show the reshaped columns of the new data frame
ds.colnames("core_yearlyrep_1_3_wide", datasources = conns)
#> $armadillo
#>  [1] "row_id"            "child_id"          "cohab_"            "occup_m_"          "occupcode_m_"      "edu_m_"            "occup_f1_"        
#>  [8] "occup_f1_fath"     "occup_f2_"         "occup_f2_fath"     "occupcode_f1_"     "occupcode_f1_fath" "occupcode_f2_"     "occupcode_f2_fath"
#> [15] "edu_f1_"           "edu_f1_fath"       "edu_f2_"           "edu_f2_fath"       "childcare_"        "childcarerel_"     "childcareprof_"   
#> [22] "childcarecentre_"  "smk_exp"           "cats_quant_"       "dogs_quant_"       "mental_exp"        "hhincome_"         "fam_splitup"      
#> [29] "famsize_child"     "famsize_adult"     "pets_.0"           "cats_.0"           "dogs_.0"           "pets_.1"           "cats_.1"          
#> [36] "dogs_.1"           "pets_.2"           "cats_.2"           "dogs_.2"
```

When you reshaped and subsetted the data you often need to merge your dataframe with others to get your analysis dataframe. You can do this using the `ds.merge` function:


```r
# merge non-repeated table with wide-format repeated table
ds.merge(x.name = 'core_nonrep',
         y.name = 'core_yearlyrep_1_3_wide',
         by.x.names = 'child_id',
         by.y.names = 'child_id',
         newobj = 'analysis_df',
         datasources = conns
)
#> $is.object.created
#> [1] "A data object <analysis_df> has been created in all specified data sources"
#> 
#> $validity.check
#> [1] "<analysis_df> invalid in at least one source. See studyside.messages:"
#> 
#> $studyside.messages
#> $studyside.messages$armadillo
#> [1] "NOT ALL OK: there are studysideMessage(s) on this datasource"
```


```r
# check the columns names
ds.colnames("analysis_df", datasources = conns)
#> Error: The input vector must be of type 'data.frame' or a 'matrix'!
```

### Performing analysis
There are a variety of analysis you can perform in DataSHIELD. You can perform basic merthods such as summary statistics and more advanced methods susch as GLM.

#### Simple statistical methods
You execute a summary on the a variable within you analysis frame. It will return summary statistics.


```r
ds.summary("analysis_df$pets_.1", datasources = conns)
#> Error: The input object must be a 'data.frame', 'character', factor', 'integer', 'list', 'logical', 'matrix' or 'numeric'.
```

#### Advanced statistical methods
When you finished the analysis dataframe, you can perform the actual analysis. You can use a wide variety of functions. The example below is showing the `glm`. After that you can create a 


```r
datashield.assign.table(conns = conns,
                        table = "gecko/1_1-outcome-1_0/nonrep",
                        symbol = "outcome_nonrep")

armadillo_glm <- ds.glm(formula = 'asthma_ever_CHICOS~pets_preg',
        data = 'outcome_nonrep',
        family = 'binomial',
        datasources = conns)
#> 
#> 
#> MODEL FITTING TERMINATED AT FIRST ITERATION:
#> Any values of 1 in the following tables denote potential disclosure risks
#> please use the argument <datasources> to include only valid studies.
#> Errors by study are as follows:
#>           Y VECTOR
#> armadillo        0
#>           [,1] [,2]
#> armadillo    0    0
#>           WEIGHT VECTOR
#> armadillo             0
#>           OFFSET VECTOR
#> armadillo             0
#>           MODEL OVERPARAMETERIZED
#> armadillo                       1
#>           ERROR MESSAGES                                       
#> armadillo "STUDY DATA OR APPLIED MODEL INVALID FOR THIS SOURCE"
```

Do the meta analysis and install prerequisites.


```r
install.packages("metafor")
#> Error in install.packages : Updating loaded packages
```


```r
# meta analysis
yi <- c(armadillo_glm$coefficients["pets_preg", "Estimate"])
sei <- c(armadillo_glm$coefficients["pets_preg", "Std. Error"])

# random effects model:
res <- metafor::rma(yi, sei = sei)
#> Error in metafor::rma(yi, sei = sei): Specify the desired outcome measure via the 'measure' argument.
res
#> Error in eval(expr, envir, enclos): object 'res' not found
metafor::forest(res, xlab = "OR", transf = exp, refline = 1, slab = c("armadillo_glm"))
#> Error in metafor::forest(res, xlab = "OR", transf = exp, refline = 1, : object 'res' not found
```

#### Creating figures
You can directly create figures with the DataSHIELD methods. For example:


```r
ds.contourPlot(x = "outcome_nonrep$asthma_ever_CHICOS", y = "outcome_nonrep$pets_preg", datasources = conns)
```


```r
# cleanup the session
datashield.logout(conns)
```

### Workspaces
To store the assigned data in the Armadillo service, you can use workspaces to make sure a certain state of the data is maintained on the service.

Saving the workspaces can be done during `datashield.logout` or at runtime.


```r
conns <- datashield.login(login = logindata)
#> 
#> Logging into the collaborating servers

# reassign data from a Armadillo table
datashield.assign.table(conns = conns,
                        table = "gecko/2_1-core-1_0/nonrep",
                        symbol = "J",
                        variables = c("recruit_age", "child_id"))
#> ```

```
#>   Assigned all table (J <- ...) [========================================================] 100% / 0s

# save the workspace duringg logout
datashield.logout(conns, save = "my-workspace")
#>   Logged out from all servers [==========================================================] 100% / 0s

# restore workspace during logging in
conns <- datashield.login(logins = logindata, 
                          assign = FALSE, 
                          restore = "my-workspace")
#> 
#> Logging into the collaborating servers
#>   Logged in all servers [================================================================] 100% / 0s

# check if the workspace is restored correctly
# should contain 'J'
datashield.symbols(conns)
#> $armadillo
#> [1] "J"

# save workspace at runtime
datashield.workspace_save(conns, "my-workspace-version-2")
```

You can overwrite workspaces using the same name again when saving the workspace.


```r
# make sure we start with an empty workspace
datashield.logout(conns)
#>   Logged out from all servers [==========================================================] 100% / 0s
conns <- datashield.login(logins = logindata)
#> 
#> Logging into the collaborating servers

# assign data to make sure something is in the workspace
datashield.assign.table(conns = conns, 
                        table = "gecko/2_1-core-1_0/nonrep", 
                        symbol = "H")
#>   Assigned all table (H <- ...) [========================================================] 100% / 0s

datashield.workspace_save(conns, "my-workspace-overwritten")
datashield.workspace_save(conns, "my-workspace-overwritten")
```

You can list the workspaces as well.


```r
# list all workspaces for this user
datashield.workspaces(conns$armadillo)
#>             lastAccessDate                               ETag                               name   size user
#> 1 2020-08-28T07:44:38.236Z "79ea8e26a41a0f43716040c5f09466c0" armadillo:my-workspace-overwritten 172072     
#> 2 2020-08-28T07:44:36.572Z "7de51b96e6d15e9ab13b9ef52fe3547f"   armadillo:my-workspace-version-2   3610     
#> 3 2020-08-28T07:44:35.773Z "7de51b96e6d15e9ab13b9ef52fe3547f"             armadillo:my-workspace   3610
```

Remove workspaces.


```r
# create a new workspace 
datashield.workspace_rm(conns, "my-workspace-overwritten")
# list the workspaces to make sure the overwritten one is deleted
datashield.workspaces(conns)
#>      server name..armadillo.my.workspace.version.2. name..armadillo.my.workspace. user lastAccessDate..2020.08.28T07.44.36.572Z.
#> 1 armadillo        armadillo:my-workspace-version-2        armadillo:my-workspace                       2020-08-28T07:44:36.572Z
#> 2 armadillo        armadillo:my-workspace-version-2        armadillo:my-workspace                       2020-08-28T07:44:36.572Z
#>   lastAccessDate..2020.08.28T07.44.35.773Z. size.3610L size.3610L.1
#> 1                  2020-08-28T07:44:35.773Z       3610         3610
#> 2                  2020-08-28T07:44:35.773Z       3610         3610
```
